### ISSUE TITLE
Monitoring/alerting for Kosmoo itself

### ISSUE THREAD

**Issue by MPV** [mercedes-benz/kosmoo#104]
I've seen the nice suggested alerts over at:
https://github.com/mercedes-benz/kosmoo/blob/master/docs/alerts.md

**How do you monitor (and alert on) that Kosmoo is working as it should?**

**Comment by MPV** [comment]
I've made a first draft of a related alert:
```yaml
        # OpenStack reachable by Kosmoo:
        - alert: KosmooOpenStackScrapeFailures
          annotations:
            summary: "[Kosmoo] OpenStack scrape failures"
            description: >
              Kosmoo has been unable to scrape OpenStack. See logs for more details.
          expr: |
            absent(kos_scrape_status_succeeded) or (kos_scrape_status_succeeded == 0)
          for: 6m
          labels:
            severity: critical
```

**Comment by seanschneeweiss** [comment]
Thank you for your input. Feedback unfortunately takes a bit longer than usual, as we are preparing for KubeCon :)

We'll get back to you as soon as possible.

**Comment by seanschneeweiss** [comment]
We define a `livenessProbe` for the kosmoo deployment.
```yaml
livenessProbe:
  failureThreshold: 3
  httpGet:
    path: /healthz
    port: 9183
    scheme: HTTP
  initialDelaySeconds: 5
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 5
```

We use kube-state-metrics for alerting on deployments where the specified replicas do not match the available replicas.
Also kube-state-metrics is used for alerting on pod phase "Pending" or a pods that have too many restarts.

This is the alert for the Kosmoo scrape:
```yaml
- name: openstack
  rules:
  - alert: OpenStackExporterScrapeFailed
    expr: scrape_status_succeeded{app="kosmoo"} == 0
    for: 30m
    labels:
      severity: warning
      context: "{{$labels.tenant}} {{$labels.kubernetes_io_hostname}} {{$labels.kubernetes_pod_name}}"
    annotations:
      summary: "Kosmoo failed scraping metrics from OpenStack for more than 30 minutes."
      impact: "Cinder metrics for tenant {{$labels.tenant}} cannot be scraped."
      action: "Check the logs of the Kosmoo pod on {{$labels.tenant}} in namespace {{$labels.kubernetes_namespace}}. It might be that AuthN endpoint on OpenStack is not working."
```
